ontologies:
  source:
    - url: 'https://spec.edmcouncil.org/fibo/ontology/MetadataFIBO/'
    - url: 'https://spec.edmcouncil.org/fibo/ontology/AboutFIBODev/'
    - path: staticOntologies
  catalog_path:
    - ontologies/catalog-v001.xml
  module_ignore_pattern:
    - '^(About|Metadata|Load).*'
    - 'http.*(About|Metadata).*'